-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 13:54:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema occb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema occb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `occb` DEFAULT CHARACTER SET utf8 ;
USE `occb` ;

-- -----------------------------------------------------
-- Table `occb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `occb`.`user` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `dateRegistered` DATETIME NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `occb`.`relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `occb`.`relationship` (
  `relationshioID` INT NOT NULL AUTO_INCREMENT,
  `user_userID` INT NOT NULL,
  `user_userID2` INT NOT NULL,
  PRIMARY KEY (`relationshioID`, `user_userID`, `user_userID2`),
  INDEX `fk_relationship_user_idx` (`user_userID` ASC) VISIBLE,
  INDEX `fk_relationship_user1_idx` (`user_userID2` ASC) VISIBLE,
  CONSTRAINT `fk_relationship_user`
    FOREIGN KEY (`user_userID`)
    REFERENCES `occb`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relationship_user1`
    FOREIGN KEY (`user_userID2`)
    REFERENCES `occb`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `occb`.`userSetting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `occb`.`userSetting` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `user_userID` INT NOT NULL,
  `notifRecipeFeed` ENUM('ON', 'OFF') NULL,
  `notifFollower` ENUM('ON', 'OFF') NULL,
  `notifComment` ENUM('ON', 'OFF') NULL,
  `privacy` ENUM('ON', 'OFF') NULL,
  PRIMARY KEY (`userID`, `user_userID`),
  INDEX `fk_userSetting_user1_idx` (`user_userID` ASC) VISIBLE,
  CONSTRAINT `fk_userSetting_user1`
    FOREIGN KEY (`user_userID`)
    REFERENCES `occb`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `occb`.`userProfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `occb`.`userProfile` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `user_userID` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `gender` CHAR NULL,
  `DOB` DATE NULL,
  `about` TEXT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC) VISIBLE,
  INDEX `fk_userProfile_user1_idx` (`user_userID` ASC) VISIBLE,
  CONSTRAINT `fk_userProfile_user1`
    FOREIGN KEY (`user_userID`)
    REFERENCES `occb`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `occb`.`recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `occb`.`recipe` (
  `recipeID` INT NOT NULL AUTO_INCREMENT,
  `user_userID` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `instruction` TEXT NULL,
  `ingredients` TEXT NULL,
  `datePublished` DATETIME NULL,
  PRIMARY KEY (`recipeID`, `user_userID`),
  INDEX `fk_recipe_user1_idx` (`user_userID` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_user1`
    FOREIGN KEY (`user_userID`)
    REFERENCES `occb`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `occb`.`cookBook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `occb`.`cookBook` (
  `cookBookID` INT NOT NULL AUTO_INCREMENT,
  `categoryID` INT NULL,
  `recipe_recipeID` INT NOT NULL,
  `recipe_user_userID` INT NOT NULL,
  PRIMARY KEY (`cookBookID`),
  UNIQUE INDEX `categoryID_UNIQUE` (`categoryID` ASC) VISIBLE,
  INDEX `fk_cookBook_recipe1_idx` (`recipe_recipeID` ASC, `recipe_user_userID` ASC) VISIBLE,
  CONSTRAINT `fk_cookBook_recipe1`
    FOREIGN KEY (`recipe_recipeID` , `recipe_user_userID`)
    REFERENCES `occb`.`recipe` (`recipeID` , `user_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `occb`.`mealCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `occb`.`mealCategory` (
  `categoryID` INT NOT NULL AUTO_INCREMENT,
  `mealCategory` VARCHAR(45) NOT NULL,
  `cookBook_cookBookID` INT NOT NULL,
  PRIMARY KEY (`categoryID`),
  INDEX `fk_mealCategory_cookBook1_idx` (`cookBook_cookBookID` ASC) VISIBLE,
  CONSTRAINT `fk_mealCategory_cookBook1`
    FOREIGN KEY (`cookBook_cookBookID`)
    REFERENCES `occb`.`cookBook` (`cookBookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `occb`.`recipeCommet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `occb`.`recipeCommet` (
  `recipeCommentID` INT NOT NULL AUTO_INCREMENT,
  `comment` TEXT NOT NULL,
  `datePublished` DATETIME GENERATED ALWAYS AS () VIRTUAL,
  `recipe_recipeID` INT NOT NULL,
  `recipe_user_userID` INT NOT NULL,
  PRIMARY KEY (`recipeCommentID`),
  INDEX `fk_recipeCommet_recipe1_idx` (`recipe_recipeID` ASC, `recipe_user_userID` ASC) VISIBLE,
  CONSTRAINT `fk_recipeCommet_recipe1`
    FOREIGN KEY (`recipe_recipeID` , `recipe_user_userID`)
    REFERENCES `occb`.`recipe` (`recipeID` , `user_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
